num_thread: 10
num_game_per_thread: 120
replay_buffer_size: 50000
burn_in_frames: 10000
train_device: cuda:0
act_device: cuda:1
vdn: 0
num_epoch: 1000
epoch_len: 500
act_base_eps: 0.1
gamma: 0.999
multi_step: 1
net: drrn-lstm
aux_weight: 0
llm_prior:
pikl_beta: 1
pikl_lambda: 0.15
shuffle_color: 0
target_data_ratio: 2
load_model: #/home/mila/n/nekoeiha/MILA/Zeroshot_hanabi_instructrl_mtl_5/pyhanabi/~/scratch/llm_hanabi_hive/exps/test_mtl5_loaded_no_eval/loaded_epoch120.pthw_np_2_lora_dim_0_text_enc_pretrained_s_48950461/epoch120.pthw_np_2_lora_dim_0_text_enc_pretrained_s_48950461/epoch100.pthw
save_per: 20
batchsize: 64
max_len: 80
rnn_hid_dim: 128
num_player: 2
do_eval: 0
save_dir: ~/scratch/llm_hanabi_hive/exps/test_mtl5_1layer/
wandb: 1
update_freq_text_enc: 1
lm_weights: pretrained
num_of_additional_layer: 0
num_lm_layer: 1
lora_dim: 0
