num_thread: 40
num_game_per_thread: 120
replay_buffer_size: 50000
burn_in_frames: 10000 #00
train_device: cuda:0
act_device: cuda:1
vdn: 0
num_epoch: 2000
epoch_len: 500
act_base_eps: 0.1
gamma: 0.999
net: publ-lstm
aux_weight: 0
llm_prior:
pikl_beta: 1
pikl_lambda: 0.15
shuffle_color: 0
target_data_ratio: 2
load_model:
save_per: 50
batchsize: 96
max_len: 80
num_player: 2
do_eval: 1
save_dir: ~/scratch/llm_hanabi_hive/baseline_exps/
wandb: 0
