num_thread: 32
num_game_per_thread: 120
replay_buffer_size: 50000
burn_in_frames: 10000
train_device: cuda:0
act_device: cuda:0
vdn: 0
num_epoch: 1000
epoch_len: 200
act_base_eps: 0.1
gamma: 0.999
multi_step: 1
net: drrn-lstm
aux_weight: 0
llm_prior:
pikl_beta: 1
pikl_lambda: 0.15
shuffle_color: 0
target_data_ratio: 2
# load_model: scratch/llm_hanabi_hive/exps8/epoch175.pthw
save_per: 25
batchsize: 64
max_len: 80
rnn_hid_dim: 128
num_player: 2
do_eval: 1
save_dir: scratch/llm_hanabi_hive/exps11/
wandb: 0
update_freq_text_enc: 1
lm_weights: pretrained
num_of_additional_layer: 0
lora_dim: 0

eval_num_game: 100 # num of games to take avg when eval
